bundler_args: --without development --path vendor/bundle
before_script:
  - "mysql -e 'create database fanarts_test;'"
script: "bundle exec rake db:drop db:create db:migrate spec"
rvm:
  - 1.9.2
gemfile:
  - Gemfile
branches:
  only:
    - develop
env:
  - DB=mysql
