bundler_args: --without development
before_script:
  - "mysql -e 'create database fanarts_test;'"
script: 'bundle exec rake spec'
rvm:
  - 1.9.2
gemfile:
  - Gemfile
branches:
  only:
    - develop
env:
  - DB=mysql