development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: fanarts
  username: root
  password: root
  socket: /Applications/MAMP/tmp/mysql/mysql.sock

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: fanarts
  username: fanarts
  password: fanarts
  socket: /var/run/mysqld/mysqld.sock