development:
  adapter: mysql2
  database: fanarts_development
  username:
  encoding: utf8
  host: 127.0.0.1

test:
  adapter: mysql2
  database: fanarts_test
  username:
  encoding: utf8
  host: 127.0.0.1

production:
  adapter: mysql2
  encoding: utf8
  database: fanarts
  username: fanarts
  password: fanarts
  socket: /var/run/mysqld/mysqld.sock
