development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: fanarts
  username: root
  password: root
  socket: /Applications/MAMP/tmp/mysql/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: fanarts_test
  username: root
  password: root
  socket: /Applications/MAMP/tmp/mysql/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: fanarts
  username: fanarts
  password: fanarts
  socket: /var/run/mysqld/mysqld.sock

mysql:
  adapter: mysql2
  database: fanarts_test
  username:
  encoding: utf8
